### ISSUE TITLE
customer_activity_statement_monthly -- filter negative balances

### ISSUE THREAD

**Issue by travish2** [odoonz/odoonz-addons#3]
https://github.com/odoonz/odoonz-addons/blob/ac8ca60527eb52d9d2b1de5ae87db4729c9d5bfd/customer_activity_statement_monthly/report/customer_activity_statement.py#L59

Hello, thank you for the module, much better than what I had cobbled together. Only suggestion is that the line ` if v > 0.0 and k in partner_ids` should be >= 0.0 to print partners that did not have any transactions in the past month but still have overdue amounts

**Comment by gdgellatly** [comment]
@travish2 that shouldn't be correct because Amount Due gets its initial balance from the balances brought forward so it should not matter. see here https://github.com/OCA/account-financial-reporting/blob/ce377fdf7e81812e75b7d1076378f930de4bc29c/customer_activity_statement/report/customer_activity_statement.py#L353
